global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  # Phase 1 以降でコンテナを追加したらここに足す
  # - job_name: origin
  #   static_configs:
  #     - targets: ["origin:8080"]
